### ISSUE TITLE
Create release for linux

### ISSUE THREAD

**Issue by dhzdhd** [dhzdhd/ExCode#1]

**Comment by gilice** [comment]
Hey! I'd love to work on this!

**Comment by dhzdhd** [comment]
> Hey! I'd love to work on this!

Sure!
By creating a release for linux i mean creating a github workflow for linux.

**Comment by gilice** [comment]
@dhzdhd Do you want the linux build to be merged into `build-windows-and-android`, or in a seperate job?

Merging would allow to create a release with all the files (windows, linux, android) in one place.
