### ISSUE TITLE
application icons

### ISSUE THREAD

**Issue by gilice** [dhzdhd/ExCode#16]
There currently isn't an application icon. Although `assets` includes a picture, it isn't set for any platform, they use the default flutter one.
https://github.com/dhzdhd/ExCode/blob/master/assets/icons/logo.png

Proposal:
- I can make an icon for all platforms analogue to the one already there.

Or, is this being worked on behind the scenes?

**Comment by dhzdhd** [comment]
I am planning to change the icon for future releases so the icon choice is not very important right now.
