### ISSUE TITLE
Text not visible due to same color as background

### ISSUE THREAD

**Issue by lakshay007** [dhzdhd/ExCode#21]
"Code" and "Output" Text isn't visible on the mobile web version due to same the color of the background  which is White as well
![Screenshot_2022-10-14-22-24-05-81_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/34618792/195901558-65c7c3e6-cb2a-40d4-a099-16ddf74f215e.jpg)

**Comment by DHRUVA-N-L-CHOUDHARY** [comment]
@lakshay007  can you please assign me the issue. I am eager to work on it.

**Comment by DHRUVA-N-L-CHOUDHARY** [comment]
![image](https://user-images.githubusercontent.com/96297602/196503466-4d3245c4-e4ac-4d29-bc6d-85354c99a85b.png)
